/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omalv
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
public class ViewEntry extends javax.swing.JFrame {

    /**
     * Creates new form ViewEntry
     */
    private int uid;
    public ViewEntry(int uid,String date, String entryText) {
        initComponents();
        jTextField2.setText(date);
        jTextField1.setText(entryText);
        this.uid = uid;

        String entryDate = date;

        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (updateEntry(date, jTextField1.getText(),jTextField2.getText())) {
                    JOptionPane.showMessageDialog(ViewEntry.this, "Update Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                    home homeFrame = new home(uid);
                    homeFrame.initializeAndShow();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(ViewEntry.this, "Update Failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (deleteEntry(date)) {
                    JOptionPane.showMessageDialog(ViewEntry.this, "Delete Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                    home homeFrame = new home(uid);
                    homeFrame.initializeAndShow();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(ViewEntry.this, "Delete Failed", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
//        jTextField2.setText(entryText);
        // Set the title of the frame as the date or any other information you want to display.
    }
    private boolean deleteEntry(String date) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/birthdays", "root", "1234");
            String query = "DELETE FROM entries WHERE date = ?";
            PreparedStatement stmt = conn.prepareStatement(query);

            stmt.setString(1, date);

            int deletedRows = stmt.executeUpdate();

            stmt.close();
            conn.close();

            return deletedRows > 0;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
        
    private boolean updateEntry(String date, String newName,String newDate) {
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/birthdays", "root", "1234");
            String query = "UPDATE entries SET name = ?,date = ? WHERE date = ?";
            PreparedStatement stmt = conn.prepareStatement(query);
            // Convert the date to the "yy-MM-dd" format
            SimpleDateFormat outputFormat = new SimpleDateFormat("yy-MM-dd");
            
            stmt.setString(1, newName);
            stmt.setString(2,outputFormat.format(newDate));
            stmt.setString(3, date);

            int updatedRows = stmt.executeUpdate();

            stmt.close();
            conn.close();

            return updatedRows > 0;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 240, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 180, 50));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bright Blue Stars Galaxy Desktop Wallpaper.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home homeFrame = new home(uid);
        homeFrame.initializeAndShow();dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
